# demo configuration
random_state: 123

model:
  max_length: 256
  model_name: distilbert-base-uncased
  padding: max_length
  return_tensors: pt
  truncation: True

metrics:
  - name: f1_score
  - name: balanced_accuracy_score

training:
  dataset_path: ../../../data/imdb/train.csv
  validation_dataset_path: ../../../data/imdb/validation.csv
  selectors:
    - args: { }
      name: dummy
  batch_size: 2
  epochs: 6
  learning_rate: 1e-5
  metric_for_best_model: f1_score
  perform_data_cartography: True


testing:
  dataset_path: ../../../data/imdb/test.csv
  selectors: [ ]
  results_file: ./file_test_results.pickle

control:
  dataset_path: ../../../data/imdb/control.csv
  results_file: ./file_control_results.pickle
