# demo configuration

model:
  max_length: 256
  model_name: bert-base-cased
  num_labels: 12
  padding: max_length
  return_tensors: pt
  truncation: True

metrics:
  - name: f1
    args:
      average: macro
  - name: slicing
    args: 
      result_file: '../../data/slicing/slicing.pickle'
      base_directory: "../../data/slicing/"
      default_file_name: "slicing.pickle"
        

training:
  dataset_path: ../../data/featuresets/thedeep.subset.train.txt
  selectors:
    - args: { }
      name: dummy
    - args: { result_file: '../../data/slicing/train_slicing.pickle'}
      name: slicing
  batch_size: 2
  epochs: 1
  learning_rate: 1e-3
  validation_size: 0.2
  output_dir: ClassificationBERT
  metric_for_best_model: f1

testing:
  dataset_path: ../../data/featuresets/thedeep.subset.test.txt
  selectors: 
    - args: { result_file: '../../data/slicing/test_slicing.pickle'}
      name: slicing
  results_file: ./file_test_results.pickle

control:
  dataset_path: ../../data/featuresets/thedeep.subset.control.txt
  results_file: ./file_control_results.pickle
