# demo configuration

model:
  max_length: '256'
  model_name: bert-base-cased
  num_labels: '12'
  padding: max_length
  return_tensors: pt
  truncation: 'True'

training:
  dataset_path: ../../data/thedeep.subset.train.txt
  selectors:
    - args: { }
      name: DUMMY
  batch_size: '2'
  epochs: '1'
  learning_rate: 1e-3
  output_dir: ClassificationBERT

testing:
  dataset_path: ../../data/thedeep.subset.test.txt
  selectors: [ ]
  results_file: ./file_test_results.pickle
  metrics:
    - name: accuracy

control:
  dataset_path: ../../data/thedeep.subset.control.txt
  results_file: ./file_control_results.pickle
  metrics:
    - name: accuracy
