# demo configuration
random_state: 123

model:
  max_length: 256
  model_name: bert-base-cased
  num_labels: 12
  padding: max_length
  return_tensors: pt
  truncation: True

metrics:
  - name: f1_score
    args:
      average: macro

training:
  dataset_path: ../../data/thedeep/train.txt
  has_header: False
  text_column_id: 1
  label_column_id: 2
  selectors:
    - args: { }
      name: dummy
  batch_size: 8
  epochs: 2
  learning_rate: 1e-3
  validation_size: 0.2
  output_dir: ClassificationBERT
  metric_for_best_model: f1_score

testing:
  dataset_path: ../../data/thedeep/test.txt
  has_header: False
  text_column_id: 1
  label_column_id: 2
  selectors: [ ]
  results_file: ./file_test_results.pickle

control:
  dataset_path: ../../data/thedeep/control.txt
  has_header: False
  text_column_id: 1
  label_column_id: 2
  results_file: ./file_control_results.pickle
