# demo configuration
random_state: 123
data_dir: "../../data/featuresets/"

model:
  max_length: 256
  model_name: distilbert-base-uncased
  num_labels: 12
  padding: max_length
  return_tensors: pt
  truncation: True

metrics:
  - name: f1_score
    args:
      average: macro
  - name: slicing_scores
    args: 
      base_directory: 'slicing/'
      default_file_name: "slicing.pickle"
        

training:
  dataset_path: 'thedeep.subset.train.txt'
  selectors:
    - name: dummy
      args: { }
    - name: slicing
      args: 
        result_file: 'slicing/train_slicing.pickle'
        list_of_slicing_functions: [short, textblob_polarity, long]
  results_file: 'results/file_train_results.pickle'
  batch_size: 2
  epochs: 1
  learning_rate: 1e-3
  validation_size: 0.2
  output_dir: ClassificationBERT
  metric_for_best_model: f1_score

testing:
  dataset_path: 'thedeep.subset.test.txt'
  selectors: 
    - name: slicing
      args: 
        result_file: 'slicing/test_slicing.pickle'
      
  results_file: 'results/file_test_results.pickle'

control:
  dataset_path: 'thedeep.subset.control.txt'
  results_file: 'results/file_control_results.pickle'

mlflow:
  experiment_name: 'my_experiment_slicing'
  tags:
      version: 'v1'
  tracking_uri: "http://localhost:5000"

