name: build

on: pull_request

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Check file formatting
        uses: lgeiger/black-action@v1.0.1
        with:
          args: -l 120 --check ./src

      - name: Prepare devcontainer.json from template
        run: mv ./.devcontainer/devcontainer.json.template ./.devcontainer/devcontainer.json

      - name: Build and run dev container
        uses: devcontainers/ci@v0.3
