name: format-check

on: pull_request

jobs:
  check-code-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: lgeiger/black-action@v1.0.1
        with:
          args: -l 120 --check ./src
